"""add_celery_task_to_race

Revision ID: 8d186d4c2c25
Revises: 58b91be3d785
Create Date: 2024-01-11 23:45:46.065163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision: str = '8d186d4c2c25'
down_revision: Union[str, None] = '58b91be3d785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True))
    op.alter_column('season', 'end_timestamp',
               existing_type=oracle.DATE(),
               nullable=True)
    op.drop_constraint("season_timestamp_order", "season")
    op.create_check_constraint("season_timestamp_order", "season", "end_timestamp is null or end_timestamp > start_timestamp")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('season', 'end_timestamp',
               existing_type=oracle.DATE(),
               nullable=False)
    op.drop_column('race', 'celery_task_id')
    op.drop_constraint("season_timestamp_order", "season")
    op.create_check_constraint("season_timestamp_order", "season", "end_timestamp > start_timestamp")
    # ### end Alembic commands ###
