"""initialize_models

Revision ID: add81a84830b
Revises: dedfd641436a
Create Date: 2023-11-23 19:41:00.770132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'add81a84830b'
down_revision: Union[str, None] = 'dedfd641436a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('rider', 'coordinator', 'admin', name='accounttype'), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('surname', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.CheckConstraint("type in ('rider', 'coordinator', 'admin')", name="account_type_enum"),
    sa.CheckConstraint("gender in ('male', 'female')", name="account_gender_enum")
    )
    op.create_table('classificationaccesslimiter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('rule', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('racebonus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('rule', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('points_multiplier', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('start_timestamp', sa.DateTime(), nullable=False),
    sa.Column('end_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.CheckConstraint("end_timestamp > start_timestamp", name="season_timestamp_order")
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coordinator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('rending', 'in_progress', 'ended', name='racestatus'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('requirements', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('checkpoints_gpx_file', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('start_timestamp', sa.DateTime(), nullable=False),
    sa.Column('end_timestamp', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Enum('cold', 'normal', 'hot', name='racetemperature'), nullable=True),
    sa.Column('rain', sa.Enum('zero', 'light', 'heavy', name='racerain'), nullable=True),
    sa.Column('wind', sa.Enum('zero', 'light', 'heavy', name='racewind'), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkpoints_gpx_file'),
    sa.CheckConstraint("end_timestamp > start_timestamp", name="race_timestamp_order"),
    sa.CheckConstraint("temperature in ('cold', 'normal', 'hot')", name="race_temperature_enum"),
    sa.CheckConstraint("rain in ('zero', 'light', 'heavy')", name="race_rain_enum"),
    sa.CheckConstraint("wind in ('zero', 'light', 'heavy')", name="race_wind_enum"),
    sa.CheckConstraint("status in ('pending', 'in_progress', 'ended')", name="race_status_enum")
    )
    op.create_table('rider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accesslimiterclassificationlink',
    sa.Column('access_limiter_id', sa.Integer(), nullable=False),
    sa.Column('classification_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['access_limiter_id'], ['classificationaccesslimiter.id'], ),
    sa.ForeignKeyConstraint(['classification_id'], ['classification.id'], ),
    sa.PrimaryKeyConstraint('access_limiter_id', 'classification_id')
    )
    op.create_table('bike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('type', sa.Enum('road', 'fixie', 'other', name='biketype'), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rider_id'], ['rider.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint("type in ('road', 'fixie', 'other')", name="bike_type_enum")
    )
    op.create_table('racebonusracelink',
    sa.Column('race_bonus_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['race_bonus_id'], ['racebonus.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('race_bonus_id', 'race_id')
    )
    op.create_table('riderclassificationlink',
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('classification_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classification_id'], ['classification.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['rider.id'], ),
    sa.PrimaryKeyConstraint('rider_id', 'classification_id'),
    sa.CheckConstraint("score >= 0", name="rider_classification_link_score_non_negative")
    )
    op.create_table('raceparticipation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='raceparticipationstatus'), nullable=False),
    sa.Column('place_generated', sa.Integer(), nullable=True),
    sa.Column('place_assigned', sa.Integer(), nullable=True),
    sa.Column('ride_start_timestamp', sa.DateTime(), nullable=True),
    sa.Column('ride_end_timestamp', sa.DateTime(), nullable=True),
    sa.Column('ride_gpx_file', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('bike_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bike_id'], ['bike.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['rider.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint("status in ('pending', 'approved', 'rejected')", name="race_participation_status_enum"),
    sa.CheckConstraint("place_generated > 0", name="race_participation_place_generated_positive"),
    sa.CheckConstraint("place_assigned > 0", name="race_participation_place_assigned_positive"),
    sa.CheckConstraint("ride_end_timestamp > ride_start_timestamp", name="race_participation_timestamp_order"),
    sa.CheckConstraint("ride_end_timestamp IS NOT NULL", name="race_participation_gpx_requires_timestamp")

    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raceparticipation')
    op.drop_table('riderclassificationlink')
    op.drop_table('racebonusracelink')
    op.drop_table('bike')
    op.drop_table('accesslimiterclassificationlink')
    op.drop_table('rider')
    op.drop_table('race')
    op.drop_table('coordinator')
    op.drop_table('classification')
    op.drop_table('admin')
    op.drop_table('season')
    op.drop_table('racebonus')
    op.drop_table('classificationaccesslimiter')
    op.drop_table('account')
    # ### end Alembic commands ###
