"""Initialize database

Revision ID: dedfd641436a
Revises: 
Create Date: 2023-11-17 12:52:53.190249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dedfd641436a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('bar', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dummy')
    # ### end Alembic commands ###
