"""add_race_details

Revision ID: e78fd565fc94
Revises: add81a84830b
Create Date: 2023-11-27 21:13:27.172443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e78fd565fc94'
down_revision: Union[str, None] = 'add81a84830b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('dummy')
    op.execute("DROP TABLE IF EXISTS dummy")
    op.add_column('coordinator', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.add_column('race', sa.Column('meetup_timestamp', sa.DateTime(), nullable=True))
    op.add_column('race', sa.Column('entry_fee_gr', sa.Integer(), nullable=False))
    op.add_column('race', sa.Column('event_graphic_file', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False))
    op.add_column('race', sa.Column('place_to_points_mapping_json', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False))
    op.add_column('race', sa.Column('sponsor_banners_uuids_json', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True))
    op.create_unique_constraint(None, 'race', ['event_graphic_file'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'race', type_='unique')
    op.drop_column('race', 'sponsor_banners_uuids_json')
    op.drop_column('race', 'place_to_points_mapping_json')
    op.drop_column('race', 'event_graphic_file')
    op.drop_column('race', 'entry_fee_gr')
    op.drop_column('race', 'meetup_timestamp')
    op.drop_column('coordinator', 'phone_number')
    op.create_table('dummy',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('foo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('bar', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='sys_c008342')
    )
    # ### end Alembic commands ###
