ALTER SEQUENCE bike_seq NOCACHE
ALTER SEQUENCE classification_seq NOCACHE
ALTER SEQUENCE race_seq NOCACHE
ALTER SEQUENCE racebonus_seq NOCACHE
ALTER SEQUENCE raceparticipation_seq NOCACHE
ALTER SEQUENCE season_seq NOCACHE
ALTER SEQUENCE account_seq NOCACHE