name: pytest

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Oracle container image registry
      uses: docker/login-action@v3
      with:
        registry: container-registry.oracle.com
        username: ${{ secrets.ORACLE_REGISTRY_USERNAME }}
        password: ${{ secrets.ORACLE_REGISTRY_PASSWORD }}
    - name: Set up environment
      run: |
        chmod +x setup.sh
        ./setup.sh
    - name: Build container images
      run: |
        docker compose build --build-arg "BUILD_ENV=test"
    - name: Run containers in detached mode
      run: |
        docker compose up --detach
    - name: Wait for startup   # todo not too elegant
      run: |
        sleep 30
    - name: Check for pending migrations
      run: |
        docker exec fastapi-backend bash -c "alembic check"
    - name: Run pytest
      run: |
        docker exec fastapi-backend "pytest"
