name: pytest

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main project repo
      uses: actions/checkout@v3
      with:
        repository: SNURTEL/23z-pzsp2-sigmacats
        submodules: true
        token: ${{ secrets.CLONE_TOKEN }}
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Setup project
      run: |
        chmod +x setup.sh
        ./setup.sh
    - name: Switch to feature branch if exists
      run: |
        git fetch origin
        git checkout ${{ steps.extract_branch.outputs.branch }} || true
    - name: Checkout backend
      uses: actions/checkout@v3
      with:
        repository: SNURTEL/sigmacats-backend
        token: ${{ secrets.CLONE_TOKEN }}
        path: backend
        ref: ${{ steps.extract_branch.outputs.branch }}
    - name: Login to Oracle container image registry
      uses: docker/login-action@v3
      with:
        registry: container-registry.oracle.com
        username: ${{ secrets.ORACLE_REGISTRY_USERNAME }}
        password: ${{ secrets.ORACLE_REGISTRY_PASSWORD }}
    - name: Build container images
      run: |
        docker compose build --build-arg "BUILD_ENV=test"
    - name: Run containers in detached mode
      run: |
        docker compose up --detach
    - name: Wait for startup   # todo not too elegant
      run: |
        sleep 30
    - name: Check for pending migrations
      run: |
        docker exec fastapi-backend bash -c "alembic check"
    - name: Run pytest
      run: |
        docker exec fastapi-backend bash -c "pytest -vv"
    - name: Dump container logs
      if: always()
      run: |
        docker compose logs >> container-logs.txt
    - name: Archive container logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: container-logs
        path: container-logs.txt
        retention-days: 7
